CREATE TABLE users_roles(
    id BIGINT generated by default as identity,
    user_id BIGINT,
    role_id BIGINT,
    PRIMARY KEY(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);